server:
  port: 8080

spring:
  application:
    name: gateway-demo
  cloud:
    gateway:
      routes:
      - id: method_route
        uri: http://localhost:8085/
        predicates:
        ## 转发地址格式为 uri/archive，/str 部分会被下面的过滤器给截取掉
        - Path=/portal-demo/sayHelloworld2
#        filters:
#        ## 截取路径位数
#        - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

