server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config-server-demo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huanghaijian1/springcloud-demo/
          search-paths: /config-server-demo/src/main/resources/springcloud-config/config-repo/
          username: huanghaijian1
          password: HHJian2447816806
