server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config-server-demo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huanghaijian1/springcloud-demo/
          label: master
          search-paths: /config-server-demo/config-repo/
          username:
          password:
