server:
  port: 8085
spring:
  application:
    name: portal-demo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#开启Feign Hystrix 支持
feign:
  hystrix:
    enabled: true #开启Feign Hystrix 支持
hystrix:
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 30000
        requestVolumeThreshold: 50
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 50
          thread:
            timeoutInMilliseconds: 100000

myremote:
  server:
    name: portalserver-demo
    sayHelloworld: /portal-server/sayHelloworld
    sayHelloworld2: /portal-server/sayHelloworld2
    sayHelloworld3: /portal-server/sayHelloworld3
sayHelloworldurl: http://${myremote.server.name}/${myremote.server.sayHelloworld}/{name}/{id}
sayHelloworldurl2: http://${myremote.server.name}/${myremote.server.sayHelloworld2}/
sayHelloworldurl3: http://${myremote.server.name}/${myremote.server.sayHelloworld3}