server:
  port: 8085
spring:
  application:
    name: portal-demo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

myremote:
  server:
    name: portalserver-demo
    sayHelloworld: /portal-server/sayHelloworld
    sayHelloworld2: /portal-server/sayHelloworld2
sayHelloworldurl: http://${myremote.server.name}/${myremote.server.sayHelloworld}/{name}/{id}
sayHelloworldurl2: http://${myremote.server.name}/${myremote.server.sayHelloworld2}/